name: Deploy

on:
  repository_dispatch:
    types: ["dispatch-main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # Download .war from GitHub packages
      - name: Download WAR binary from GitHub packages
        run: .github/workflows/scripts/download-war.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DBPTK_UI_VERSION: ${{ github.event.client_payload.version }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up tags
        run: |
          echo "FULL_TAG=v${{ github.event.client_payload.version }}" >> $GITHUB_ENV
          echo "MAJOR_TAG=$(awk -F. '{print "v"$1}' <<< "${{ github.event.client_payload.version }}")" >> $GITHUB_ENV
          echo "MAJOR_MINOR_TAG=$(awk -F. '{print "v"$1"."$2}' <<< "${{ github.event.client_payload.version }}")" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            keeps/dbvtk:${{ env.FULL_TAG }}
            keeps/dbvtk:${{ env.MAJOR_MINOR_TAG }}
            keeps/dbvtk:${{ env.MAJOR_TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
